//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzinsizGirisDT
    {
        public int ID { get; set; }
        public System.Guid GirenKisi { get; set; }
        public System.DateTime GirmeTarihi { get; set; }
        public string GirdigiSayfa { get; set; }
    }
}
