//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullanicilarDT
    {
        public System.Guid ID { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Resim { get; set; }
        public System.DateTime OlusturulmaTarihi { get; set; }
        public Nullable<System.Guid> OlusturanKisiID { get; set; }
        public Nullable<System.DateTime> GuncellenmeTarihi { get; set; }
        public Nullable<System.Guid> GuncelleyenKisiID { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public Nullable<System.Guid> SilenKisiID { get; set; }
        public bool AktifMi { get; set; }
    }
}
