//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormTable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormTableDBEntities : DbContext
    {
        public FormTableDBEntities()
            : base("name=FormTableDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IzinsizGirisDT> IzinsizGirisDT { get; set; }
        public virtual DbSet<KullanicilarDT> KullanicilarDT { get; set; }
        public virtual DbSet<DersDT> DersDT { get; set; }
        public virtual DbSet<FormDT> FormDT { get; set; }
        public virtual DbSet<SinifNoDT> SinifNoDT { get; set; }
    }
}
