//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinifNoDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinifNoDT()
        {
            this.FormDTs = new HashSet<FormDT>();
        }
    
        public int ID { get; set; }
        public string SinifNo { get; set; }
        public System.DateTime OlusturulmaTarihi { get; set; }
        public Nullable<System.Guid> OlusturanKisiID { get; set; }
        public Nullable<System.DateTime> GuncellenmeTarihi { get; set; }
        public Nullable<System.Guid> GuncelleyenKisiID { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public Nullable<System.Guid> SilenKisiID { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDT> FormDTs { get; set; }
    }
}
